### ISSUE TITLE
Design About page

### ISSUE THREAD

**Issue by elliothimmelfarb** [kevinhealy/split-it#3]
We need to know what this will look like

**Comment by kevinhealy** [comment]
This is going to be largely (if not entirely) a static HTML page.  It will explain what it is and how it works.  The only links, that I can predict, will be those that redirect them to the Create or View page.

It will probably have some screenshots of the Create and View page.  It will definitely have some simple diagrams that I can create in photoshop.

Since it is going to be explaining how it works, we should probably focus on the View page first.  ...because how it works isn't solidified as it depends on how the view page comes together.

**Comment by elliothimmelfarb** [comment]
This is continued on #4
